version: "3"
services:
  elasticsearch:
    container_name: hello-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
    volumes:
      - /home/pht/Desktop/code/learn-elasticsearch/data-es:/usr/share/elasticsearch/data

  kibana:
    container_name: hello-kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://hello-elasticsearch:9200
    ports:
      - 5601:5601

#volumes:
#  data-es:
#    driver: ./data-es
